export const instructors = [
  {
    id: 1,
    name: "Abebe Bikila",
    bio: "Pioneering marathon runner and national hero, now teaching the discipline and endurance needed for coding.",
    rating: 4.9,
    studentCount: 1250,
    courseCount: 3,
    avatarUrl: "https://i.pravatar.cc/150?img=68",
  },
  {
    id: 2,
    name: "Fatima al-Fihri",
    bio: "Founder of the world's oldest university, now empowering students with the ancient art of modern web development.",
    rating: 4.8,
    studentCount: 2800,
    courseCount: 5,
    avatarUrl: "https://i.pravatar.cc/150?img=49",
  },
  {
    id: 3,
    name: "Chinua Achebe",
    bio: "A master storyteller, weaving compelling narratives in literature and now in user interface design.",
    rating: 4.9,
    studentCount: 3200,
    courseCount: 4,
    avatarUrl: "https://i.pravatar.cc/150?img=60",
  },
  {
    id: 4,
    name: "Wangari Maathai",
    bio: "Nobel laureate who planted trees and now cultivates budding developers through green coding practices.",
    rating: 5.0,
    studentCount: 5000,
    courseCount: 6,
    avatarUrl: "https://i.pravatar.cc/150?img=45",
  },
];

export const categories = [
  { id: 1, name: "Web Development" },
  { id: 2, name: "Data Science" },
  { id: 3, name: "UI/UX Design" },
  { id: 4, name: "Mobile Development" },
  { id: 5, name: "Digital Marketing" },
  { id: 6, name: "Graphic Design" },
  { id: 7, name: "Video Editing" },
  { id: 8, name: "Data Analytics" },
];

export const courses = [
  {
    id: 1,
    title: "Modern React from Scratch",
    description: "A comprehensive guide to React, from fundamentals to advanced concepts.",
    instructorId: 1,
    categoryId: 1,
    price: 3500,
    imageUrl: "https://images.unsplash.com/photo-1599507593499-a3f7d7d97667?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Web Development",
    duration: "12 Weeks",
    rating: 4.7,
  },
  {
    id: 2,
    title: "Python for Data Analysis",
    description: "Unlock the power of data with Python, Pandas, and NumPy.",
    instructorId: 2,
    categoryId: 2,
    price: 4500,
    imageUrl: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Data Science",
    duration: "10 Weeks",
    rating: 4.9,
  },
  {
    id: 3,
    title: "UI/UX Design Principles",
    description: "Master the art of creating beautiful and intuitive user interfaces.",
    instructorId: 3,
    categoryId: 3,
    price: 2800,
    imageUrl: "https://storage.googleapis.com/dala-prod-public-storage/generated-images/c384fdab-b01d-47e7-b329-ebe16b155cae/ui-ux-design-principles-z9jsotb-1767461295336.webp",
    category: "UI/UX Design",
    duration: "8 Weeks",
    rating: 4.8,
  },
  {
    id: 4,
    title: "iOS Development with Swift",
    description: "Build your first iOS application from scratch using Swift and Xcode.",
    instructorId: 4,
    categoryId: 4,
    price: 5500,
    imageUrl: "https://images.unsplash.com/photo-1551650975-87deedd944c3?q=80&w=2798&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Mobile Development",
    duration: "16 Weeks",
    rating: 4.9,
  },
  {
    id: 5,
    title: "Advanced Tailwind CSS",
    description: "Deep dive into Tailwind CSS for professional and scalable designs.",
    instructorId: 1,
    categoryId: 1,
    price: 3800,
    imageUrl: "https://images.unsplash.com/photo-1617042375876-a13e36732a04?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Web Development",
    duration: "6 Weeks",
    rating: 4.9,
  },
  {
    id: 6,
    title: "SEO & Digital Marketing",
    description: "Learn the secrets of ranking on Google and growing your online presence.",
    instructorId: 2,
    categoryId: 5,
    price: 2500,
    imageUrl: "https://images.unsplash.com/photo-1557862921-37829c790f19?q=80&w=2942&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Digital Marketing",
    duration: "8 Weeks",
    rating: 4.7,
  },
  {
    id: 7,
    title: "Full-Stack Web Development",
    description: "Become a full-stack developer by learning front-end and back-end technologies.",
    instructorId: 1,
    categoryId: 1,
    price: 5800,
    imageUrl: "https://storage.googleapis.com/dala-prod-public-storage/generated-images/c384fdab-b01d-47e7-b329-ebe16b155cae/full-stack-web-development-8uykmci-1767461324170.webp",
    category: "Web Development",
    duration: "20 Weeks",
    rating: 4.9,
  },
  {
    id: 8,
    title: "Graphic Design for Beginners",
    description: "Learn the fundamentals of graphic design and create stunning visuals.",
    instructorId: 3,
    categoryId: 6,
    price: 1900,
    imageUrl: "https://storage.googleapis.com/dala-prod-public-storage/generated-images/c384fdab-b01d-47e7-b329-ebe16b155cae/graphic-design-for-beginners-tjobdlb-1767461302244.webp",
    category: "Graphic Design",
    duration: "6 Weeks",
    rating: 4.8,
  },
  {
    id: 9,
    title: "Video Editing with Premiere Pro",
    description: "Master video editing and create professional-quality videos with Adobe Premiere Pro.",
    instructorId: 4,
    categoryId: 7,
    price: 3200,
    imageUrl: "https://storage.googleapis.com/dala-prod-public-storage/generated-images/c384fdab-b01d-47e7-b329-ebe16b155cae/video-editing-premiere-pro-clnm2kc-1767461309788.webp",
    category: "Video Editing",
    duration: "8 Weeks",
    rating: 4.9,
  },
  {
    id: 10,
    title: "Data Analytics with Power BI",
    description: "Turn complex data into beautiful visualizations and unlock insights with Power BI.",
    instructorId: 2,
    categoryId: 8,
    price: 4200,
    imageUrl: "https://storage.googleapis.com/dala-prod-public-storage/generated-images/c384fdab-b01d-47e7-b329-ebe16b155cae/data-analytics-power-bi-qva3vid-1767461317527.webp",
    category: "Data Analytics",
    duration: "10 Weeks",
    rating: 4.9,
  },
];
